base_url = "https://csaatechnicalarts.github.io/rust-graph-databases/"
title = "Workingman's Graph Databases "
description = ""
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [
	{ name = "tags" },
    { name = "kuzudb" },
    { name = "neo4j" },
]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "kronuz"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/csaatechnicalarts/rust-graph-databases/"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/tags", url = "/tags", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/csaatechnicalarts/rust-graph-databases", icon = "github" },
]

stylesheets = [
    # "custom.css"    # at /static/custom.css
]

